### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by DezarM** [tuarua/Facebook-ANE#3]
Hi
i cath this error when try login

`
Error: can't call function login
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua.facebook::LoginManager/login()[/Users/eoinlandy/flash/Facebook-ANE/native_extension/src/com/tuarua/facebook/LoginManager.as:27]

`

my code
`
var permissions:Vector.<String> = new <String>[Permission.publicProfile, Permission.email];
            loginManager.loginBehavior = LoginBehavior.nativeWithFallback;
            loginManager.login(permissions, onLoginSuccess, onLoginCancel, onLoginError);

`

**Comment by tuarua** [comment]
I am not seeing any problems on my side.

Your code is 3 lines long ?
Where is the call to FacebookSdk.init ?

Double check you followed the setup on the readme page correctly and also studied the example project.

If you are still getting errors then run logcat to see what the native error is on the device.

**Comment by DezarM** [comment]
my code
`
    trace("FacebookSdk.sdkVersion", FacebookSdk.sdkVersion);
        FacebookSdk.init("111111111111", onCurrentAccessTokenChanged);
        FacebookSdk.isDebugEnabled = true;
        trace("FacebookSdk.isInitialized:", FacebookSdk.isInitialized);
        if (!FacebookSdk.isInitialized) return;
        trace("FacebookSdk.hashKey:", FacebookSdk.hashKey);

        FacebookSdk.onShareSuccess = onShareSuccess;
        FacebookSdk.onShareCancel = onShareCancel;
        FacebookSdk.onShareError = onShareError;
		
		
            loginManager = FacebookSdk.loginManager;
            var permissions:Vector.<String> = new <String>[Permission.publicProfile, Permission.email];
            loginManager.loginBehavior = LoginBehavior.nativeWithFallback;
            loginManager.login(permissions, onLoginSuccess, onLoginCancel, onLoginError);
`


my logcat
`
2019-09-30 23:40:54.372 1054-1064/? E/Sensors: new setDelay handle(0),ns(10000000)m, error(0), index(2)
2019-09-30 23:40:54.450 25064-25116/? E/GraphResponse: GraphRequest can't be used when Facebook SDK isn't fully initialized
2019-09-30 23:40:54.452 25064-25119/? E/GraphResponse: GraphRequest can't be used when Facebook SDK isn't fully initialized
2019-09-30 23:40:54.455 25064-25120/? E/GraphResponse: GraphRequest can't be used when Facebook SDK isn't fully initialized
2019-09-30 23:40:54.466 25064-25119/? E/GraphResponse: GraphRequest can't be used when Facebook SDK isn't fully initialized
2019-09-30 23:40:54.466 25064-25120/? E/GraphResponse: GraphRequest can't be used when Facebook SDK isn't fully initialized
2019-09-30 23:40:54.542 25064-25119/? E/GraphResponse: GraphRequest can't be used when Facebook SDK isn't fully initialized
2019-09-30 23:40:54.554 25064-25064/? E/com.tuarua.FacebookANE: can't call function login
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91)
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6271)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/FacebookActivity;
        at com.facebook.login.LoginManager.getFacebookActivityIntent(LoginManager.java:689)
        at com.facebook.login.LoginManager.tryFacebookActivity(LoginManager.java:664)
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:601)
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510)
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400)
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.ClassNotFoundException: com.facebook.FacebookActivity
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginManager.getFacebookActivityIntent(LoginManager.java:689) 
        at com.facebook.login.LoginManager.tryFacebookActivity(LoginManager.java:664) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:601) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/BaseFragmentActivityApi16;
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97)
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120)
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622)
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588)
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.BaseFragmentActivityApi16
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/BaseFragmentActivityApi14;
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.BaseFragmentActivityApi14
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/SupportActivity;
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.ClassNotFoundException: android.support.v4.app.SupportActivity
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleOwner;
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleOwner" on path: DexPathList[[zip file "/data/app/com.name.name-1/base.apk"],nativeLibraryDirectories=[/data/app/com.name.name-1/lib/arm64, /data/app/com.name.name-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.login.LoginClient.getLoginRequestCode(LoginClient.java:97) 
        at com.facebook.login.LoginLogger.logStartLogin(LoginLogger.java:120) 
        at com.facebook.login.LoginManager.logStartLogin(LoginManager.java:622) 
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:588) 
        at com.facebook.login.LoginManager.logIn(LoginManager.java:510) 
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:400) 
        at com.tuarua.facebookane.KotlinController.login(KotlinController.kt:222) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tuarua.frekotlin.FreKotlinContext$CallKotlinFunction.call(FreKotlinContext.java:91) 
        at com.adobe.air.customHandler.callTimeoutFunction(Native Method) 
        at com.adobe.air.customHandler.handleMessage(customHandler.java:22) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:208) 
        at android.app.ActivityThread.main(ActivityThread.java:6271) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
2019-09-30 23:41:17.593 1054-1149/? E/WifiStateMachine: mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
2019-09-30 23:41:17.610 1054-1151/? E/WifiScanningService: WifiSingleScanStateMachine IdleState enter

`

**Comment by DezarM** [comment]
and my trace in adobe animated
`
FacebookSdk.sdkVersion 5.1.0
FacebookSdk.isInitialized: true
FacebookSdk.hashKey: WInFiAmDnXJXW7********=

Error: can't call function login
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.tuarua.facebook::LoginManager/login()[/Users/eoinlandy/flash/Facebook-ANE/native_extension/src/com/tuarua/facebook/LoginManager.as:27]

`

**Comment by DezarM** [comment]
my bad.
i foggot about android.arch.lifecycle.runtime
ANE working ,TY
